# Generated by Django 3.2.2 on 2021-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_links', '0006_alter_staticlink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticlink',
            name='file',
            field=models.FileField(upload_to='static_links'),
        ),
    ]
