# Generated by Django 3.1.7 on 2021-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_text',
        ),
        migrations.AddField(
            model_name='link',
            name='hyperlink',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='link',
            name='website_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
