# Generated by Django 3.2 on 2021-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
