# Generated by Django 3.1.7 on 2021-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210406_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
